// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDt_lzqLgp2U6IqG7wdW40JCJ9lLSn4O3U',
    appId: '1:573920900587:web:94274f607e934f6f0095ae',
    messagingSenderId: '573920900587',
    projectId: 'ditonton-9ee46',
    authDomain: 'ditonton-9ee46.firebaseapp.com',
    storageBucket: 'ditonton-9ee46.appspot.com',
    measurementId: 'G-WXNKGFX0Q6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqQ9tOTNTAPzYEVYXVBeFbiaFykAeZYNY',
    appId: '1:573920900587:android:ba3ac449b2cde73a0095ae',
    messagingSenderId: '573920900587',
    projectId: 'ditonton-9ee46',
    storageBucket: 'ditonton-9ee46.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2Yy0xmCCx-WT3gpgReFiYsSRGDuRHDCY',
    appId: '1:573920900587:ios:c0d663cc23c6ff1d0095ae',
    messagingSenderId: '573920900587',
    projectId: 'ditonton-9ee46',
    storageBucket: 'ditonton-9ee46.appspot.com',
    iosClientId:
        '573920900587-0ugl9nm0alqndjp1cnlvbernqp462oic.apps.googleusercontent.com',
    iosBundleId: 'com.dicoding.ditonton',
  );
}
